### ISSUE TITLE
Remove Image Outline Highlight

### ISSUE THREAD

**Issue by yishiy** [micheleriva/vue-product-spinner#40]
Hi,

I want to ask for help on how to remove the outline highlight when the image is focused.

Tried many different combinations but no one worked:

.vue-product-spinner img:focus{
  outline: none;
}

picture{
  outline: none;
}

.vue-product-spinner img{
  outline: none;
}

Or is there any class I can use to select those images within vue-product-spinner class?

**Comment by micheleriva** [comment]
```css
.vue-product-spinner img {
  outline: none;
}
```

this works well on the demo.
If you're using single page components with scoped css, try as follows:

```css
/deep/.vue-product-spinner img {
  outline: none;
}
```
